- name: creating ec2 instances on AWS
  hosts: localhost
  roles:
  - create_spark_cluster

- name: installing apache spark
  hosts: tag_sw_spark
  roles:
  - common
  - spark_common

- name: configuring spark master node
  hosts: tag_role_spark_master
  roles:
  - common
  - spark_master

- name: installing apache hadoop slaves
  hosts: tag_role_spark_slave
  roles:
  - { role: setup_hadoop, hadoop_node_type: slave}

- name: installing apache hadoop master node
  hosts: tag_role_spark_master
  roles:
  - { role: setup_hadoop, hadoop_node_type: master}
