- name: download apache spark binary
  sudo: yes
  get_url: url={{ spark_binary_url }} dest="/tmp/spark-{{ spark_version }}.tgz"

- name: extract downloaded spark binary
  sudo: yes
  unarchive: copy=no src="/tmp/spark-{{ spark_version }}.tgz" dest=/opt/

- name: create symbolic link to spark installation
  sudo: yes
  file: src=/opt/spark-{{ spark_version }} dest={{ spark_root }} state=link

- name: config standalone deploy mode in Spark
  sudo: yes
  template: src=conf/spark-environment.sh.j2 dest={{ spark_root }}/conf/spark-environment.sh mode="u=rwx,g=rx,o=rx"
  tags: config_spark
