- name: Install pre-req packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - wget
    - gzip
    - build-essential
    - tar
    - python-dev
    - python-pip

- name: Install pip packages
  sudo: yes
  pip: name={{ item }} state=latest
  with_items:
    - nltk
    - mongo-connector
