- name: set timezone to MST
  sudo: yes
  copy:
    content: "US/Denver\n"
    dest: /etc/timezone
  notify: restart cron

- name: update the tzdata
  sudo: yes
  command: "/usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata"
  changed_when: false